### ISSUE TITLE
ext conf google.indexing_api causes error on saving postings

### ISSUE THREAD

**Issue by peerlight** [itx-informationssysteme/jobapplications#47]
When Extension Configuration google.indexing_api is on then saving a posting (new or existing) causes this error:

```
Oops, an error occurred!
Table 'DBNAME.tx_jobapplications_domain_model_ttcontent' doesn't exist
```

with 
- PHP-Version 7.2.24
- TYPO3 9.5.30
- jobapplications 1.0.3

seems to occur when this hook is used
```
\n#5 /SERVERPATH/public_html/cms/typo3conf/ext/jobapplications/Classes/Hooks/TCEmainHook.php(95): ITX\\Jobapplications\\Utility\\GoogleIndexingApiConnector->updateGoogleIndex(7)

\n#6 /SERVERPATH/public_html/typo3_src-9.5.28/typo3/sysext/core/Classes/DataHandling/DataHandler.php(1269): ITX\\Jobapplications\\Hooks\\TCEmainHook->processDatamap_postProcessFieldArray('update', 'tx_jobapplicati...', 7, Array, Object(TYPO3\\CMS\\Core\\DataHandling\\DataHandler))
```

in TYPO3 log  I also see this (JSON_THROW_ON_ERROR is part of PHP 7.3 but we are on PHP 7.2):

```
Core: Error handler (BE): PHP Warning: Use of undefined constant JSON_THROW_ON_ERROR - assumed 'JSON_THROW_ON_ERROR' (this will throw an Error in a future version of PHP) in /SERVERPATH/public_html/cms/typo3conf/ext/jobapplications/Classes/Utility/GoogleIndexingApiConnector.php line 79 

Core: Error handler (BE): PHP Warning: json_decode() expects parameter 4 to be integer, string given in /SERVERPATH/public_html/cms/typo3conf/ext/jobapplications/Classes/Utility/GoogleIndexingApiConnector.php line 79 

Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1472074485: Table 'diakonie-1.tx_jobapplications_domain_model_ttcontent' doesn't exist | TYPO3\CMS\Extbase\Persistence\Generic\Storage\Exception\SqlErrorException thrown in file /SERVERPATH/public_html/typo3_src-9.5.28/typo3/sysext/extbase/Classes/Persistence/Generic/Storage/Typo3DbBackend.php in line 375. Requested URL: https://www.herrnhuter-diakonie.de/typo3/index.php?...
```

**Comment by itx-benjamin-jasper** [comment]
I can't reproduce the error, did you update your php version and did that solve anything? It this is still an issue please reopen.
